vich_uploader:
    db_driver: orm # or mongodb or phpcr

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    metadata:
        type: attribute

    mappings:
        candidate:
            uri_prefix: /images/candidates
            upload_destination: '%kernel.project_dir%/public/images/candidates'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        candidate_cv:
            uri_prefix: /files/candidates
            upload_destination: '%kernel.project_dir%/public/files/candidates'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        vacancy:
            uri_prefix: /images/vacancies
            upload_destination: '%kernel.project_dir%/public/images/vacancies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true